### ISSUE TITLE
Expected 123 Cycles, but only 92 bases found in SAM records

### ISSUE THREAD

**Issue by pocession** [epigen/scifiRNA-seq#12]
Hi, thanks for providing scifiRNA-seq and the analysis pipeline. I have some difficulties in demulatiplexing. In the second stage, there are some error messages thrown back. It seems there some 31nt missed. Not sure how this happened. I append some error messages here. Could you share any experience with me?

```INFO    2022-12-12 01:29:08     IlluminaSamDemux        

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    IlluminaSamDemux -INPUT  /ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi/demultiplexed/unmultiplexed.bam -OUTPUT_DIR  /ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi/demultiplexed -OUTPUT_PREFIX  scifi -LIBRARY_PARAMS  /ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi/samplesheet.tsv -METRICS_FILE  /ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi_matrix.csv -TMP_DIR ./tmp -COMPRESSION_LEVEL 9 -CREATE_MD5_FILE true -OUTPUT_FORMAT bam -BARCODE_TAG_NAME BC -BARCODE_QUALITY_TAG_NAME QT -MAX_MISMATCHES 1 -MIN_MISMATCH_DELTA 1 -MAX_NO_CALLS 2 -MINIMUM_BASE_QUALITY 0 -VERBOSITY INFO -QUIET false -VALIDATION_STRINGENCY STRICT -MAX_RECORDS_IN_RAM 500000 -CREATE_INDEX false -GA4GH_CLIENT_SECRETS client_secrets.json -USE_JDK_DEFLATER false -USE_JDK_INFLATER false -DEFLATER_THREADS 4 -MATCHING_THREADS 4 -READ_STRUCTURE  8M13B8S8B16M70T -TAG_PER_MOLECULAR_INDEX RX -TAG_PER_MOLECULAR_INDEX r2
**********


01:29:08.429 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/App/picard-2.19.2-CeMM-all.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Dec 12 01:29:08 CET 2022] IlluminaSamDemux INPUT=/ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi/demultiplexed/unmultiplexed.bam OUTPUT_DIR=/ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi/demultiplexed OUTPUT_PREFIX=scifi OUTPUT_FORMAT=bam BARCODE_TAG_NAME=BC BARCODE_QUALITY_TAG_NAME=QT LIBRARY_PARAMS=/ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi/samplesheet.tsv METRICS_FILE=/ceph/rimlsfnwi/data/cellbio/mhlanga/thsieh/scifi_matrix.csv MAX_MISMATCHES=1 MIN_MISMATCH_DELTA=1 MAX_NO_CALLS=2 MINIMUM_BASE_QUALITY=0 READ_STRUCTURE=8M13B8S8B16M70T TAG_PER_MOLECULAR_INDEX=[RX, r2] MATCHING_THREADS=4 TMP_DIR=[./tmp] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=9 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=true GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false DEFLATER_THREADS=4    ADAPTERS_TO_CHECK=[INDEXED, DUAL_INDEXED, NEXTERA_V2, FLUIDIGM] MOLECULAR_INDEX_TAG=RX MOLECULAR_INDEX_BASE_QUALITY_TAG=QX CELL_INDEX_TAG=CB CELL_INDEX_BASE_QUALITY_TAG=CY
[Mon Dec 12 01:29:08 CET 2022] Executing as thsieh@cn45 on Linux 5.15.0-56-generic amd64; OpenJDK 64-Bit Server VM 11.0.17+8-post-Ubuntu-1ubuntu220.04; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.19.2-CeMM
INFO    2022-12-12 01:29:08     IlluminaSamDemux        Writer was started
INFO    2022-12-12 01:29:08     IlluminaSamDemux        Executor was started with 4 threads
Exception in thread "Thread-0" picard.PicardException: Error while processing records 
        at picard.illumina.IlluminaSamDemux$ReadsWriter.run(IlluminaSamDemux.java:605)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at picard.illumina.IlluminaSamDemux$ReadsWriter.run(IlluminaSamDemux.java:567)
        ... 1 more
Caused by: picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.illumina.SamToSamMapper.convertClusterToOutputRecord(SamToSamMapper.java:286)
        at picard.illumina.IlluminaSamDemux$BarcodeMatcher.processRecord(IlluminaSamDemux.java:681)
        at picard.illumina.IlluminaSamDemux$BarcodeMatchJob.call(IlluminaSamDemux.java:522)
        at picard.illumina.IlluminaSamDemux$BarcodeMatchJob.call(IlluminaSamDemux.java:508)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
ERROR   2022-12-12 01:29:08     ThreadPoolExecutorWithExceptions        
ERROR   2022-12-12 01:29:08     ThreadPoolExecutorWithExceptions        
picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.util.ThreadPoolExecutorWithExceptions.afterExecute(ThreadPoolExecutorWithExceptions.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.util.ThreadPoolExecutorWithExceptions.afterExecute(ThreadPoolExecutorWithExceptions.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1129)
        ... 2 more
Caused by: picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.illumina.SamToSamMapper.convertClusterToOutputRecord(SamToSamMapper.java:286)
        at picard.illumina.IlluminaSamDemux$BarcodeMatcher.processRecord(IlluminaSamDemux.java:681)
        at picard.illumina.IlluminaSamDemux$BarcodeMatchJob.call(IlluminaSamDemux.java:522)
        at picard.illumina.IlluminaSamDemux$BarcodeMatchJob.call(IlluminaSamDemux.java:508)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        ... 2 more

Exception: picard.PicardException thrown from the UncaughtExceptionHandler in thread "pool-3-thread-1"
ERROR   2022-12-12 01:29:09     ThreadPoolExecutorWithExceptions        
picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.util.ThreadPoolExecutorWithExceptions.afterExecute(ThreadPoolExecutorWithExceptions.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.util.ThreadPoolExecutorWithExceptions.afterExecute(ThreadPoolExecutorWithExceptions.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1129)
        ... 2 more
Caused by: picard.PicardException: Expected 123 Cycles, but only 92 bases found in SAM records
        at picard.illumina.SamToSamMapper.convertClusterToOutputRecord(SamToSamMapper.java:286)
        at picard.illumina.IlluminaSamDemux$BarcodeMatcher.processRecord(IlluminaSamDemux.java:681)
        at picard.illumina.IlluminaSamDemux$BarcodeMatchJob.call(IlluminaSamDemux.java:522)
        at picard.illumina.IlluminaSamDemux$BarcodeMatchJob.call(IlluminaSamDemux.java:508)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        ... 2 more
```

**Comment by pocession** [comment]
I found that problem is caused by a setting different from your original usage.
